### ISSUE TITLE
why the `unique()`? 

### ISSUE THREAD

**Issue by paulilli** [jquery/jquery-release#81]
This line https://github.com/jquery/jquery-release/blob/master/lib/contributors.js#L6. It seems strange. Why not to use something like the `array-unique` module? It's considered best practice to have individual runnable functions in a separated (and tested!) module. Also, it's way more performant.

**Comment by arschmitz** [comment]
Because we only need this here. It is not needed any where else and including a module is an awful lot  for a 5 line function. Performance is not a concern this is only run when we do releases and this is a trivial function anyway. Im going to close this @scottgonzalez feel free to re open if you don't agree

**Comment by paulilli** [comment]
That's generally not how the community goes about that. I know people writing node modules for one-liners. I think, if you can reduce the amount of code you don't need to test/maintain you should do that.

**Comment by scottgonzalez** [comment]
It's fine as is. We don't need to test this function. It's very straight forward.
