### ISSUE TITLE
use `npm ci` instead of `npm install` to get locked dependecies

### ISSUE THREAD

**Issue by staabm** [jquery/jquery-release#99]
shouldnt this package use `npm ci` instead of `npm install` to make sure it only installs the required packages in the version which is defined in package-json.js

the release should contain what the host project defined in its package-json.js it should not try to find newer packes at release time.

see 
https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
https://docs.npmjs.com/cli/ci.html

**Comment by staabm** [comment]
This is mainly motivated by https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json

Just running `npm install` will modify the packe-lock.json as of npm 5.7.

**Comment by dmethvin** [comment]
Yes, it does seem like we should be using `npm ci` for releases. At the time it was developed I don't think the lock file even existed! Good catch though.

**Comment by mgol** [comment]
Copying in my feedback from #100: 

From the docs: https://docs.npmjs.com/cli/ci.html
> In short, the main differences between using npm install and npm ci are:
> * The project must have an existing package-lock.json or npm-shrinkwrap.json.

Many of projects released via `jquery-release` don't have a `package-lock.json` committed because of various npm bugs that make lockfile contents highly unstable. Plus, checking the lockfile in means you must settle on npm vs Yarn.

Therefore, I don't think we can use `npm ci`.

**Comment by mgol** [comment]
Closing due to the above. Sorry!
